Repository brain-tec/website, pull requests merged in 2020-11, with the labels that each got.

#275 Syncing from upstream OCA/website (13.0)
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: 13.0

#276 Syncing from upstream OCA/website (14.0)
  .copier-answers.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
Labels: 14.0

#277 Syncing from upstream OCA/website (13.0)
  .pre-commit-config.yaml
Labels: 13.0

#278 Syncing from upstream OCA/website (12.0)
  website_legal_page/i18n/fi.po
Labels: 12.0

#279 [t119317] Remove clear cache line to improve performance
  website_cookie_notice/controllers/main.py
Labels: 13.0.project_mi_582, enhancement

#280 Syncing from upstream OCA/website (11.0)
  website_google_tag_manager/__manifest__.py
  website_google_tag_manager/views/res_config_settings_view.xml
Labels: 11.0

#281 Syncing from upstream OCA/website (12.0)
  website_google_tag_manager/i18n/pt.po
Labels: 12.0

#282 Syncing from upstream OCA/website (13.0)
  website_analytics_piwik/i18n/es_AR.po
Labels: 13.0

#283 Syncing from upstream OCA/website (13.0)
  website_form_recaptcha/i18n/es_AR.po
  website_google_tag_manager/i18n/es_AR.po
Labels: 13.0

#284 Syncing from upstream OCA/website (12.0)
  website_megamenu/__manifest__.py
  website_megamenu/templates/website.xml
Labels: 12.0
